export const MAX_TENTACLES = 8;
export const SEGMENTS_PER_TENTACLE = 10;
export const ESSENCE_PER_SEGMENT = 10;
export const SEGMENTS_TYPE = 2; // segments + sucker

export const ESSENCE_PER_TENTACLE =
  SEGMENTS_PER_TENTACLE * SEGMENTS_TYPE * ESSENCE_PER_SEGMENT;
export const ESSENCE_FOR_CREATURE = MAX_TENTACLES * ESSENCE_PER_TENTACLE;
